---
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/zorin
      - MONGO_DB=zorin
    depends_on:
      - mongo

  mongo:
    image: mongo:8.2
    container_name: zorin-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0
    container_name: zorin-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_SITE_BASEURL: "/"
    depends_on:
      - mongo

volumes:
  mongo-data:
