apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zorin.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zorin.labels" . | nindent 4 }}
data:
  MONGO_URI: {{ .Values.config.MONGO_URI | quote }}
  MONGO_DB: {{ .Values.config.MONGO_DB | quote }}
