{{- if .Values.mongoExpress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zorin.fullname" . }}-mongo-express
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zorin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongoExpress.port }}
      targetPort: {{ .Values.mongoExpress.port }}
      protocol: TCP
      name: http
  selector:
    app: zorin-mongo-express
{{- end }}
