{{- if .Values.mongoExpress.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zorin.fullname" . }}-mongo-express
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zorin.labels" . | nindent 4 }}
    app: zorin-mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zorin-mongo-express
  template:
    metadata:
      labels:
        {{- include "zorin.selectorLabels" . | nindent 8 }}
        app: zorin-mongo-express
    spec:
      containers:
        - name: mongo-express
          image: "{{ .Values.mongoExpress.image.repository }}:{{ .Values.mongoExpress.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.mongoExpress.port }}
              name: web
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: {{ include "zorin.fullname" . }}-mongo
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_SITE_BASEURL
              value: "/"
          resources:
            {{- toYaml .Values.mongoExpress.resources | nindent 12 }}
{{- end }}
